api-version: 1.17
name: LobbyOstrov
main: ru.ostrov77.lobby.Main
version: 1.0
load: POSTWORLD
author: Romindous,Komiss77

depend: [Ostrov, serverfigure, LangUtils]


commands:
  oscom:
    description: Коммуникатор
  area:
    description: Добавить зону
