api-version: 1.18
name: LobbyOstrov
main: ru.ostrov77.lobby.Main
version: 1.0
load: POSTWORLD
author: Romindous,Komiss77

depend: [Ostrov, serverfigure]


commands:
  oscom:
    description: Коммуникатор
